/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        black: "var(--black)",
        "black-10": "var(--black-10)",
        "black-25": "var(--black-25)",
        "black-5": "var(--black-5)",
        "black-50": "var(--black-50)",
        "black-75": "var(--black-75)",
        dark: "var(--dark)",
        "dark-10": "var(--dark-10)",
        "dark-25": "var(--dark-25)",
        "dark-5": "var(--dark-5)",
        "dark-50": "var(--dark-50)",
        "dark-75": "var(--dark-75)",
        gray: "var(--gray)",
        primary: "var(--primary)",
        "primary-10": "var(--primary-10)",
        "primary-25": "var(--primary-25)",
        "primary-5": "var(--primary-5)",
        "primary-50": "var(--primary-50)",
        "primary-75": "var(--primary-75)",
        secondary: "var(--secondary)",
        "secondary-10": "var(--secondary-10)",
        "secondary-25": "var(--secondary-25)",
        "secondary-5": "var(--secondary-5)",
        "secondary-50": "var(--secondary-50)",
        "secondary-75": "var(--secondary-75)",
        stroke: "var(--stroke)",
        white: "var(--white)",
        "white-10": "var(--white-10)",
        "white-25": "var(--white-25)",
        "white-5": "var(--white-5)",
        "white-50": "var(--white-50)",
        "white-75": "var(--white-75)",
      },
      fontFamily: {
        body: "var(--body-font-family)",
        "body-2": "var(--body-2-font-family)",
        button: "var(--button-font-family)",
        h1: "var(--h1-font-family)",
        h2: "var(--h2-font-family)",
        h3: "var(--h3-font-family)",
        h4: "var(--h4-font-family)",
        h5: "var(--h5-font-family)",
        h6: "var(--h6-font-family)",
        "input-text": "var(--input-text-font-family)",
        "larg-paragraph": "var(--larg-paragraph-font-family)",
        overline: "var(--overline-font-family)",
        paragraph: "var(--paragraph-font-family)",
        subtitle: "var(--subtitle-font-family)",
        "subtitle-2": "var(--subtitle-2-font-family)",
      },
      boxShadow: {
        shadow: "var(--shadow)",
      },
    },
  },
  plugins: [],
};
